name: Guard RunwayML Auto Runs
on:
  workflow_run:
    workflows: ["RunwayML Video Automation for USA Market"]
    types: [requested]

env:
  # 如需临时放开自动运行，在仓库 Settings → Variables 设置 ALLOW_RUNWAY_AUTO=true
  ALLOW_RUNWAY_AUTO: ${{ vars.ALLOW_RUNWAY_AUTO || 'false' }}

permissions:
  actions: write

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Decide and cancel if needed
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const run   = context.payload.workflow_run;

            const allowAuto = (process.env.ALLOW_RUNWAY_AUTO || 'false').toLowerCase() === 'true';
            const isManual  = run.event === 'workflow_dispatch';

            core.info(`Run #${run.run_number} event=${run.event} manual=${isManual} allowAuto=${allowAuto}`);

            if (isManual || allowAuto) {
              core.notice('Manual run or ALLOW_RUNWAY_AUTO=true -> allow.');
              return;
            }

            core.notice(`Cancel non-manual run (event=${run.event}) for RunwayML workflow.`);
            await github.rest.actions.cancelWorkflowRun({ owner, repo, run_id: run.id });
