name: Merge PR by Title
on:
  workflow_dispatch:
    inputs:
      title:
        description: PR title to merge (exact match)
        required: true

permissions:
  pull-requests: write
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const title = core.getInput('title', { required: true });

            const { data: prs } = await github.rest.pulls.list({ owner, repo, state: 'open', per_page: 100 });
            const pr = prs.find(p => p.title.trim() === title.trim());
            if (!pr) core.setFailed(`PR not found: ${title}`);

            await github.rest.pulls.merge({
              owner, repo, pull_number: pr.number, merge_method: 'squash'
            });
            core.notice(`Merged PR #${pr.number}: ${pr.title}`);