name: Runway Diagnoser (Auto)

on:
  workflow_run:
    workflows: ["RunwayML Video Automation for USA Market"]
    types: [completed]

permissions:
  actions: write
  contents: write

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch logs.zip for the finished run
        id: fetch
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const runId = context.payload.workflow_run.id;
            const res = await github.request("GET /repos/{owner}/{repo}/actions/runs/{run_id}/logs", {
              owner, repo, run_id: runId,
              request: { responseType: 'arraybuffer' }
            });
            const fs = require('fs');
            fs.writeFileSync('logs.zip', Buffer.from(res.data));
            core.setOutput('run_url', context.payload.workflow_run.html_url);
            core.setOutput('run_id', String(runId));

      - name: Unzip logs
        run: |
          mkdir -p logs
          unzip -o logs.zip -d logs

      - name: Scan logs for common failures
        id: scan
        run: |
          set -e
          touch DIAGNOSIS.md
          echo "# Runway Workflow Diagnosis" >> DIAGNOSIS.md
          echo "" >> DIAGNOSIS.md
          echo "- Run URL: ${{ steps.fetch.outputs.run_url }}" >> DIAGNOSIS.md
          echo "- Run ID:  ${{ steps.fetch.outputs.run_id }}" >> DIAGNOSIS.md
          echo "" >> DIAGNOSIS.md
          echo "## Heuristics" >> DIAGNOSIS.md

          function mark() { if grep -RniE "$1" logs >/dev/null; then echo "- [x] $2" >> DIAGNOSIS.md; else echo "- [ ] $2" >> DIAGNOSIS.md; fi }

          mark "YT_CLIENT_ID|YT_CLIENT_SECRET|YT_REFRESH_TOKEN|YouTube" "YouTube 上传相关：可能缺少/无效的 Secrets（YT_CLIENT_ID/SECRET/REFRESH_TOKEN）或 API 报错"
          mark "invalid_grant|401|403" "OAuth/权限失败（invalid_grant/401/403）"
          mark "quota|rate limit" "配额/速率限制"
          mark "ffmpeg not found|codec not found" "FFmpeg/编码器缺失"
          mark "ModuleNotFoundError|ImportError|pip: not found" "Python 依赖缺失"
          mark "NotFound|ENOENT|No such file" "脚本或路径问题（文件/目录不存在）"
          mark "OpenAI|RUNWAY|api key|API key" "AI/Runway/OpenAI 等 API Key 问题"

          echo "" >> DIAGNOSIS.md
          echo "## Log Excerpts" >> DIAGNOSIS.md
          grep -RniE "invalid_grant|401|403|YT_|YouTube|quota|rate limit|ffmpeg|ModuleNotFoundError|ImportError|NotFound|ENOENT" logs | head -n 200 >> DIAGNOSIS.md || true

      - name: Upload diagnosis & logs
        uses: actions/upload-artifact@v4
        with:
          name: runway-diagnosis
          path: |
            DIAGNOSIS.md
            logs/

      - name: Post job summary
        if: always()
        run: |
          echo "## Runway Workflow Diagnosis" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat DIAGNOSIS.md >> $GITHUB_STEP_SUMMARY